#!/usr/bin/env python3
"""
Airflow DAG import script for idp

This file imports all DAGs from the installed idp package.
The actual DAG definitions are in: /opt/airflow/workspace/idp-workspace/idp/_airflow_dags_

Generated by create-dag-imports.sh
"""

import sys
import os

# Load .env file before importing anything that might use config.py
# The .env file should be at workspace root (copied during wheel installation)
try:
    from dotenv import load_dotenv
    workspace_root = "/opt/airflow/workspace/idp-workspace"
    airflow_env = os.getenv('AIRFLOW_ENV', 'dev')
    env_file_name = airflow_env
    env_file = os.path.join(workspace_root, f'.env.{env_file_name}')
    if os.path.exists(env_file):
        load_dotenv(env_file, override=True)
    else:
        # Fallback: try mounted location
        mounted_env_file = f"/workspace/infra-data-pipelines/.env.{env_file_name}"
        if os.path.exists(mounted_env_file):
            load_dotenv(mounted_env_file, override=True)
except ImportError:
    # python-dotenv not available, continue without loading .env
    pass
except Exception as e:
    # If loading fails, continue anyway
    import logging
    logging.getLogger(__name__).warning(f"Failed to load .env file: {e}")

# Add workspace root to Python path to enable imports from installed package
# Dev: package at workspace/idp-workspace/idp; test/prod: package_root/idp
workspace_root = "/opt/airflow/workspace/idp-workspace"
if workspace_root and workspace_root not in sys.path:
    sys.path.insert(0, workspace_root)

# Add /opt/airflow to Python path so 'operators' package can be imported
# (operators is at /opt/airflow/operators, so we need the parent directory)
airflow_root = "/opt/airflow"
if airflow_root and airflow_root not in sys.path:
    sys.path.insert(0, airflow_root)

# Set up storage path for DAG file writes (TA)
# Prefer TRADING_AGENT_STORAGE from .env; fallback to ta/{env}/ for compatibility
import os
airflow_env = os.getenv('AIRFLOW_ENV', 'dev')
storage_env = airflow_env
default_storage_root = f"/workspace/storage-other-data/ta/{storage_env}"
if not os.getenv('TRADING_AGENT_STORAGE'):
    os.environ['TRADING_AGENT_STORAGE'] = default_storage_root

# Import all DAG objects from the installed package
# DAGs are in {package_name}/_airflow_dags_/, which Python imports as {package_name}._airflow_dags_

# Import DAG from fred_catalog_generation_dag.py
try:
    import idp._airflow_dags_.fred_catalog_generation_dag as module
    globals()[module.dag.dag_id] = module.dag
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from idp._airflow_dags_.fred_catalog_generation_dag: {e}")

# Import DAG from edgar_master_idx_dag.py
try:
    import idp._airflow_dags_.edgar_master_idx_dag as module
    globals()[module.dag.dag_id] = module.dag
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from idp._airflow_dags_.edgar_master_idx_dag: {e}")

# Import DAG from edgar_filings_quarterly_dag.py
try:
    import idp._airflow_dags_.edgar_filings_quarterly_dag as module
    globals()[module.dag.dag_id] = module.dag
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from idp._airflow_dags_.edgar_filings_quarterly_dag: {e}")

# Import DAG from edgar_company_tickers_dag.py
try:
    import idp._airflow_dags_.edgar_company_tickers_dag as module
    globals()[module.dag.dag_id] = module.dag
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from idp._airflow_dags_.edgar_company_tickers_dag: {e}")

# Import DAG from bls_download_from_query_dag.py
try:
    import idp._airflow_dags_.bls_download_from_query_dag as module
    globals()[module.dag.dag_id] = module.dag
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from idp._airflow_dags_.bls_download_from_query_dag: {e}")

# Import DAG from eurostat_catalog_generation_dag.py
try:
    import idp._airflow_dags_.eurostat_catalog_generation_dag as module
    globals()[module.dag.dag_id] = module.dag
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from idp._airflow_dags_.eurostat_catalog_generation_dag: {e}")

# Import DAG from fred_download_from_query_dag.py
try:
    import idp._airflow_dags_.fred_download_from_query_dag as module
    globals()[module.dag.dag_id] = module.dag
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from idp._airflow_dags_.fred_download_from_query_dag: {e}")

# Import DAG from bls_generate_catalog_dag.py
try:
    import idp._airflow_dags_.bls_generate_catalog_dag as module
    globals()[module.dag.dag_id] = module.dag
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from idp._airflow_dags_.bls_generate_catalog_dag: {e}")

