#!/usr/bin/env python3
"""
Airflow DAG import script for trading_agent

This file imports all DAGs from the installed trading_agent package.
The actual DAG definitions are in: /opt/airflow/workspace/trading_agent-workspace/trading_agent/_airflow_dags_

Generated by create-dag-imports.sh
"""

import sys
import os

# Add workspace root to Python path to enable imports from installed package
workspace_root = "/opt/airflow/workspace/trading_agent-workspace"
if workspace_root and workspace_root not in sys.path:
    sys.path.insert(0, workspace_root)

# Add /opt/airflow to Python path so 'operators' package can be imported
# (operators is at /opt/airflow/operators, so we need the parent directory)
airflow_root = "/opt/airflow"
if airflow_root and airflow_root not in sys.path:
    sys.path.insert(0, airflow_root)

# Import all DAG objects from the package module
# DAGs are in trading_agent/_airflow_dags_/
# Import each module and register its DAG in the global namespace so Airflow can discover it

try:
    import trading_agent._airflow_dags_.macro_master_dag as module
    # Register the DAG in global namespace using its dag_id as the key
    globals()[module.dag.dag_id] = module.dag
except ImportError as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import DAGs from trading_agent._airflow_dags_.macro_master_dag: {e}")
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to register DAG from trading_agent._airflow_dags_.macro_master_dag: {e}")

try:
    import trading_agent._airflow_dags_.edgar_master_idx_dag as module
    globals()[module.dag.dag_id] = module.dag
except ImportError as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import DAGs from trading_agent._airflow_dags_.edgar_master_idx_dag: {e}")
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to register DAG from trading_agent._airflow_dags_.edgar_master_idx_dag: {e}")

try:
    import trading_agent._airflow_dags_.edgar_filings_quarterly_dag as module
    globals()[module.dag.dag_id] = module.dag
except ImportError as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import DAGs from trading_agent._airflow_dags_.edgar_filings_quarterly_dag: {e}")
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to register DAG from trading_agent._airflow_dags_.edgar_filings_quarterly_dag: {e}")

try:
    import trading_agent._airflow_dags_.edgar_company_tickers_dag as module
    globals()[module.dag.dag_id] = module.dag
except ImportError as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import DAGs from trading_agent._airflow_dags_.edgar_company_tickers_dag: {e}")
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to register DAG from trading_agent._airflow_dags_.edgar_company_tickers_dag: {e}")

try:
    import trading_agent._airflow_dags_.edgar_filings_dag as module
    globals()[module.dag.dag_id] = module.dag
except ImportError as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import DAGs from trading_agent._airflow_dags_.edgar_filings_dag: {e}")
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to register DAG from trading_agent._airflow_dags_.edgar_filings_dag: {e}")

try:
    import trading_agent._airflow_dags_.macro_data_downloads as module
    globals()[module.dag.dag_id] = module.dag
except ImportError as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import DAGs from trading_agent._airflow_dags_.macro_data_downloads: {e}")
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to register DAG from trading_agent._airflow_dags_.macro_data_downloads: {e}")

try:
    import trading_agent._airflow_dags_.macro_sql_workflows as module
    globals()[module.dag.dag_id] = module.dag
except ImportError as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import DAGs from trading_agent._airflow_dags_.macro_sql_workflows: {e}")
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to register DAG from trading_agent._airflow_dags_.macro_sql_workflows: {e}")