#!/usr/bin/env python3
"""
Airflow DAG import script for trading_agent

This file imports all DAGs from the installed trading_agent package.
The actual DAG definitions are in: /opt/airflow/workspace/trading_agent-workspace/trading_agent/_airflow_dags_

Generated by create-dag-imports.sh
"""

import sys
import os

# Load .env file before importing anything that might use config.py
# The .env file should be at workspace root (copied during wheel installation)
try:
    from dotenv import load_dotenv
    workspace_root = "/opt/airflow/workspace/trading_agent-workspace"
    airflow_env = os.getenv('AIRFLOW_ENV', 'dev')
    # Map staging to staging (no change needed for .env file name)
    env_file_name = 'staging' if airflow_env == 'staging' else airflow_env
    env_file = os.path.join(workspace_root, f'.env.{env_file_name}')
    if os.path.exists(env_file):
        load_dotenv(env_file, override=True)
    else:
        # Fallback: try mounted location
        mounted_env_file = f"/workspace/trading-agent/.env.{env_file_name}"
        if os.path.exists(mounted_env_file):
            load_dotenv(mounted_env_file, override=True)
except ImportError:
    # python-dotenv not available, continue without loading .env
    pass
except Exception as e:
    # If loading fails, continue anyway
    import logging
    logging.getLogger(__name__).warning(f"Failed to load .env file: {e}")

# Add workspace root to Python path to enable imports from installed package
# Package is installed at: /opt/airflow/workspace/trading_agent-workspace/trading_agent
# Dependencies are at: /opt/airflow/workspace/trading_agent-workspace/
workspace_root = "/opt/airflow/workspace/trading_agent-workspace"
if workspace_root and workspace_root not in sys.path:
    sys.path.insert(0, workspace_root)

# Set PYTHONPATH environment variable so tasks can find trading_agent module
# This is needed for subprocess calls like: python -m trading_agent.fundamentals.edgar.edgar-filings
# Tasks inherit this environment variable when they execute
existing_pythonpath = os.environ.get('PYTHONPATH', '')
os.environ['PYTHONPATH'] = workspace_root + (f":{existing_pythonpath}" if existing_pythonpath else "")

# Add source code path so DAGs can import from fundamentals, macro, etc.
# (TradingPythonAgent source is mounted at /workspace/trading-agent)
# The source has src/fundamentals/, but DAGs import trading_agent.fundamentals
# We create a trading_agent namespace that points to src
import os
import types
source_parent = "/workspace/trading-agent"
if os.path.exists(source_parent) and source_parent not in sys.path:
    sys.path.insert(0, source_parent)
    
    # Create trading_agent namespace package that points to src
    # This allows "from trading_agent.fundamentals" to work
    try:
        import src
        trading_agent_module = types.ModuleType('trading_agent')
        trading_agent_module.__path__ = [os.path.join(source_parent, 'src')]
        # Make src's submodules accessible via trading_agent
        for attr_name in dir(src):
            if not attr_name.startswith('_'):
                try:
                    attr = getattr(src, attr_name)
                    if hasattr(attr, '__module__') or isinstance(attr, types.ModuleType):
                        setattr(trading_agent_module, attr_name, attr)
                except:
                    pass
        sys.modules['trading_agent'] = trading_agent_module
    except Exception:
        # Fallback: just add src to path
        source_path = os.path.join(source_parent, 'src')
        if source_path not in sys.path:
            sys.path.insert(0, source_path)

# Add /opt/airflow to Python path so 'operators' package can be imported
# (operators is at /opt/airflow/operators, so we need the parent directory)
airflow_root = "/opt/airflow"
if airflow_root and airflow_root not in sys.path:
    sys.path.insert(0, airflow_root)

# Set up storage path for DAG file writes
# Storage is mounted at /workspace/storage/{env}/ and maps to TradingPythonAgent/storage/{env}/
# DAGs should write to this location instead of source code directories
import os
airflow_env = os.getenv('AIRFLOW_ENV', 'dev')
# Map staging to test for storage directory naming
storage_env = 'test' if airflow_env == 'staging' else airflow_env
storage_root = f"/workspace/storage/{storage_env}"
if os.path.exists(storage_root):
    # Set environment variable so DAGs can access storage path
    os.environ['TRADING_AGENT_STORAGE'] = storage_root
    # Also make it available via trading_agent module
    # This allows DAGs to use: from trading_agent import STORAGE_PATH
    if 'trading_agent' in sys.modules:
        trading_agent_module = sys.modules['trading_agent']
        trading_agent_module.STORAGE_PATH = storage_root

# Import all DAG objects from the package module
# DAGs are in {package_name}/_airflow_dags_/, which Python imports as {package_name}._airflow_dags_

# Import DAG from macro_master_dag.py
try:
    import trading_agent._airflow_dags_.macro_master_dag as module
    # Register the DAG in global namespace using its dag_id as the key
    globals()[module.dag.dag_id] = module.dag
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from trading_agent._airflow_dags_.macro_master_dag: {e}")
    # Continue with other imports even if one fails

# Import EDGAR DAG from edgar_master_idx_dag.py (direct file import to avoid SQLAlchemy conflicts)
try:
    import importlib.util
    # Use actual DAG file path (workspace or fallback location)
    dag_file_path = "/opt/airflow/workspace/trading_agent-workspace/trading_agent/_airflow_dags_/edgar_master_idx_dag.py"
    if not os.path.exists(dag_file_path):
        # Fallback: try workspace location
        dag_file_path = os.path.join(workspace_root, "trading_agent", "_airflow_dags_", "edgar_master_idx_dag.py")
    if os.path.exists(dag_file_path):
        spec = importlib.util.spec_from_file_location("trading_agent._airflow_dags_.edgar_master_idx_dag", dag_file_path)
        if spec and spec.loader:
            module = importlib.util.module_from_spec(spec)
            # Temporarily remove workspace from sys.path to avoid SQLAlchemy conflict
            workspace_in_path = workspace_root in sys.path
            if workspace_in_path:
                sys.path.remove(workspace_root)
            try:
                spec.loader.exec_module(module)
                if hasattr(module, 'dag') and module.dag:
                    globals()[module.dag.dag_id] = module.dag
            finally:
                # Restore workspace to sys.path
                if workspace_in_path and workspace_root not in sys.path:
                    sys.path.insert(0, workspace_root)
    else:
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"DAG file not found: {dag_file_path}")
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from edgar_master_idx_dag: {e}")
    # Continue with other imports even if one fails

# Import EDGAR DAG from edgar_filings_quarterly_dag.py (direct file import to avoid SQLAlchemy conflicts)
try:
    import importlib.util
    # Use actual DAG file path (workspace or fallback location)
    dag_file_path = "/opt/airflow/workspace/trading_agent-workspace/trading_agent/_airflow_dags_/edgar_filings_quarterly_dag.py"
    if not os.path.exists(dag_file_path):
        # Fallback: try workspace location
        dag_file_path = os.path.join(workspace_root, "trading_agent", "_airflow_dags_", "edgar_filings_quarterly_dag.py")
    if os.path.exists(dag_file_path):
        spec = importlib.util.spec_from_file_location("trading_agent._airflow_dags_.edgar_filings_quarterly_dag", dag_file_path)
        if spec and spec.loader:
            module = importlib.util.module_from_spec(spec)
            # Temporarily remove workspace from sys.path to avoid SQLAlchemy conflict
            workspace_in_path = workspace_root in sys.path
            if workspace_in_path:
                sys.path.remove(workspace_root)
            try:
                spec.loader.exec_module(module)
                if hasattr(module, 'dag') and module.dag:
                    globals()[module.dag.dag_id] = module.dag
            finally:
                # Restore workspace to sys.path
                if workspace_in_path and workspace_root not in sys.path:
                    sys.path.insert(0, workspace_root)
    else:
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"DAG file not found: {dag_file_path}")
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from edgar_filings_quarterly_dag: {e}")
    # Continue with other imports even if one fails

# Import EDGAR DAG from edgar_company_tickers_dag.py (direct file import to avoid SQLAlchemy conflicts)
try:
    import importlib.util
    # Use actual DAG file path (workspace or fallback location)
    dag_file_path = "/opt/airflow/workspace/trading_agent-workspace/trading_agent/_airflow_dags_/edgar_company_tickers_dag.py"
    if not os.path.exists(dag_file_path):
        # Fallback: try workspace location
        dag_file_path = os.path.join(workspace_root, "trading_agent", "_airflow_dags_", "edgar_company_tickers_dag.py")
    if os.path.exists(dag_file_path):
        spec = importlib.util.spec_from_file_location("trading_agent._airflow_dags_.edgar_company_tickers_dag", dag_file_path)
        if spec and spec.loader:
            module = importlib.util.module_from_spec(spec)
            # Temporarily remove workspace from sys.path to avoid SQLAlchemy conflict
            workspace_in_path = workspace_root in sys.path
            if workspace_in_path:
                sys.path.remove(workspace_root)
            try:
                spec.loader.exec_module(module)
                if hasattr(module, 'dag') and module.dag:
                    globals()[module.dag.dag_id] = module.dag
            finally:
                # Restore workspace to sys.path
                if workspace_in_path and workspace_root not in sys.path:
                    sys.path.insert(0, workspace_root)
    else:
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"DAG file not found: {dag_file_path}")
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from edgar_company_tickers_dag: {e}")
    # Continue with other imports even if one fails

# Import EDGAR DAG from edgar_filings_dag.py (direct file import to avoid SQLAlchemy conflicts)
try:
    import importlib.util
    # Use actual DAG file path (workspace or fallback location)
    dag_file_path = "/opt/airflow/workspace/trading_agent-workspace/trading_agent/_airflow_dags_/edgar_filings_dag.py"
    if not os.path.exists(dag_file_path):
        # Fallback: try workspace location
        dag_file_path = os.path.join(workspace_root, "trading_agent", "_airflow_dags_", "edgar_filings_dag.py")
    if os.path.exists(dag_file_path):
        spec = importlib.util.spec_from_file_location("trading_agent._airflow_dags_.edgar_filings_dag", dag_file_path)
        if spec and spec.loader:
            module = importlib.util.module_from_spec(spec)
            # Temporarily remove workspace from sys.path to avoid SQLAlchemy conflict
            workspace_in_path = workspace_root in sys.path
            if workspace_in_path:
                sys.path.remove(workspace_root)
            try:
                spec.loader.exec_module(module)
                if hasattr(module, 'dag') and module.dag:
                    globals()[module.dag.dag_id] = module.dag
            finally:
                # Restore workspace to sys.path
                if workspace_in_path and workspace_root not in sys.path:
                    sys.path.insert(0, workspace_root)
    else:
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"DAG file not found: {dag_file_path}")
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from edgar_filings_dag: {e}")
    # Continue with other imports even if one fails

# Import DAG from macro_data_downloads.py
try:
    import trading_agent._airflow_dags_.macro_data_downloads as module
    # Register the DAG in global namespace using its dag_id as the key
    globals()[module.dag.dag_id] = module.dag
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from trading_agent._airflow_dags_.macro_data_downloads: {e}")
    # Continue with other imports even if one fails

# Import DAG from macro_sql_workflows.py
try:
    import trading_agent._airflow_dags_.macro_sql_workflows as module
    # Register the DAG in global namespace using its dag_id as the key
    globals()[module.dag.dag_id] = module.dag
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from trading_agent._airflow_dags_.macro_sql_workflows: {e}")
    # Continue with other imports even if one fails

