#!/bin/bash
#
# Create DAG import scripts after wheel installation
#
# This script goes into airflow/{env}/{package_name}/.airflow_dags (or .airflow-dags)
# and creates import scripts in airflow/{env}/dags/ that import the DAGs from the installed package.
#
# Usage:
#   ./create-dag-imports.sh [dev|test|staging|prod] [package_name]
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_debug() {
    echo -e "${BLUE}[DEBUG]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Get environment and package name from arguments
ENV="${1:-dev}"
PACKAGE_NAME="${2:-trading_agent}"

# Map staging to test for directory naming
INSTALL_DIR_ENV="${ENV}"
if [ "${ENV}" = "staging" ]; then
    INSTALL_DIR_ENV="test"
fi

# Determine paths
# If running in Docker/container, use /opt/airflow paths
# Otherwise, use local paths
if [ -d "/opt/airflow/dags" ]; then
    # Inside Docker container
    WORKSPACE_ROOT="/opt/airflow/workspace"
    DAGS_DIR="/opt/airflow/dags"
else
    # Local filesystem
    WORKSPACE_ROOT="${SCRIPT_DIR}/${INSTALL_DIR_ENV}/workspace"
    DAGS_DIR="${SCRIPT_DIR}/${INSTALL_DIR_ENV}/dags"
fi

# Source directory: DAGs are in airflow/{env}/workspace/{package_name}-workspace/{package_name}/_airflow_dags_
SOURCE_DIR="${WORKSPACE_ROOT}/${PACKAGE_NAME}-workspace/${PACKAGE_NAME}/_airflow_dags_"

if [ ! -d "${SOURCE_DIR}" ]; then
    log_error "Could not find _airflow_dags_ directory"
    log_error "Expected location:"
    log_error "  - ${WORKSPACE_ROOT}/${PACKAGE_NAME}-workspace/${PACKAGE_NAME}/_airflow_dags_"
    log_error ""
    log_error "Please ensure:"
    log_error "  1. ${PACKAGE_NAME} wheel is installed to ${WORKSPACE_ROOT}/${PACKAGE_NAME}-workspace/${PACKAGE_NAME}/"
    log_error "  2. The package contains _airflow_dags_/ directory"
    exit 1
fi

log_info "Found DAGs directory: ${SOURCE_DIR}"

# Check if source directory is empty
if [ -z "$(ls -A "${SOURCE_DIR}" 2>/dev/null)" ]; then
    log_warn "Source directory is empty: ${SOURCE_DIR}"
    log_info "No DAGs to create import scripts for"
    exit 0
fi

# Create destination directory if it doesn't exist
mkdir -p "${DAGS_DIR}"

log_info "Creating DAG import scripts..."
log_info "  DAG source: ${SOURCE_DIR}"
log_info "  Import scripts: ${DAGS_DIR}"

# Find all Python DAG files in the source directory (excluding __init__.py and __pycache__)
DAG_FILES=$(find "${SOURCE_DIR}" -type f -name "*.py" ! -name "__init__.py" ! -path "*/__pycache__/*" 2>/dev/null)

if [ -z "${DAG_FILES}" ]; then
    log_warn "No Python DAG files found in ${SOURCE_DIR}"
    exit 0
fi

# Count files to import
FILE_COUNT=$(echo "${DAG_FILES}" | grep -v '^$' | wc -l | tr -d ' ')
log_info "Found ${FILE_COUNT} DAG file(s) to import"

# Create a single import script that imports all DAGs
# Script name: {package_name}_dags.py
IMPORT_SCRIPT="${DAGS_DIR}/${PACKAGE_NAME}_dags.py"

log_info "Creating import script: $(basename "${IMPORT_SCRIPT}")"

# Start building the import script
cat > "${IMPORT_SCRIPT}" <<EOF
#!/usr/bin/env python3
"""
Airflow DAG import script for ${PACKAGE_NAME}

This file imports all DAGs from the installed ${PACKAGE_NAME} package.
The actual DAG definitions are in: ${SOURCE_DIR}

Generated by create-dag-imports.sh
"""

import sys
import os

# Add workspace root to Python path to enable imports from installed package
# Package is installed at: ${WORKSPACE_ROOT}/${PACKAGE_NAME}-workspace/${PACKAGE_NAME}
# Dependencies are at: ${WORKSPACE_ROOT}/${PACKAGE_NAME}-workspace/
workspace_root = "${WORKSPACE_ROOT}/${PACKAGE_NAME}-workspace"
if workspace_root and workspace_root not in sys.path:
    sys.path.insert(0, workspace_root)

# Add /opt/airflow to Python path so 'operators' package can be imported
# (operators is at /opt/airflow/operators, so we need the parent directory)
airflow_root = "/opt/airflow"
if airflow_root and airflow_root not in sys.path:
    sys.path.insert(0, airflow_root)

# Import all DAG objects from the package module
# DAGs are in {package_name}/_airflow_dags_/, which Python imports as {package_name}._airflow_dags_

EOF

# Process each DAG file and add imports
IMPORT_COUNT=0
while IFS= read -r dag_file; do
    if [ -z "${dag_file}" ]; then
        continue
    fi
    
    # Get relative path from source directory
    rel_path="${dag_file#${SOURCE_DIR}/}"
    
    # Get base filename without extension (e.g., "my_dag.py" -> "my_dag")
    dag_basename=$(basename "${rel_path}" .py)
    
    # Get directory path (empty if DAG is directly in _airflow_dags_, or "subdir" if in subdirectory)
    rel_dir=$(dirname "${rel_path}")
    
    # Build import path
    # DAGs are in airflow/{env}/{package_name}/_airflow_dags_/
    # Python imports this as: {package_name}._airflow_dags_.{module}
    DAG_MODULE_NAME="_airflow_dags_"
    
    if [ "${rel_dir}" = "." ] || [ -z "${rel_dir}" ]; then
        # DAG is directly in the DAGs directory
        import_module="${PACKAGE_NAME}.${DAG_MODULE_NAME}.${dag_basename}"
    else
        # DAG is in a subdirectory (e.g., _airflow_dags/subdir/my_dag.py)
        # Replace slashes with dots for Python import path
        rel_dir_dots=$(echo "${rel_dir}" | tr '/' '.')
        import_module="${PACKAGE_NAME}.${DAG_MODULE_NAME}.${rel_dir_dots}.${dag_basename}"
    fi
    
    # Add import statement to the script
    # Import the module and register its DAG in global namespace so Airflow can discover it
    cat >> "${IMPORT_SCRIPT}" <<EOF
# Import DAG from ${rel_path}
try:
    import ${import_module} as module
    # Register the DAG in global namespace using its dag_id as the key
    globals()[module.dag.dag_id] = module.dag
except Exception as e:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"Failed to import/register DAG from ${import_module}: {e}")
    # Continue with other imports even if one fails

EOF
    
    IMPORT_COUNT=$((IMPORT_COUNT + 1))
    log_debug "  Added import for: ${dag_basename} (from ${import_module})"
done <<< "${DAG_FILES}"

chmod +x "${IMPORT_SCRIPT}"

log_info "✓ Created import script: $(basename "${IMPORT_SCRIPT}") with ${IMPORT_COUNT} import(s)"

log_info "Done!"
