apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: macro-cycle-hmm
  namespace: default
  annotations:
    serving.kserve.io/deploymentMode: Serverless
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 3
    mlflow:
      storageUri: "models:/macro-cycle-hmm/Staging"
      env:
        - name: MLFLOW_TRACKING_URI
          value: "http://host.docker.internal:55000"
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
